#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 12 19:51:27 2017

@author: martin
"""

import numpy as np
import matplotlib.pyplot as plt

n_iter = 300 * 1000 # cantidad de iteraciones para cada temperatura (de ising.c)
tiempo_term = 150 * 1000 #estimado del tiempo de termalizacion (a ojo)
range_temp = 10 #cantidad de temperaturas
temp_max = 5
temperatura = np.linspace(temp_max/range_temp, temp_max, range_temp)
n = 32

datos = np.load('32_datos.npy')

rho_m_01 = np.load('B_01_J-1_rho_m.npy')
rho_e_01 = np.load('B_01_J-1_rho_e.npy')

rho_prom_m_01 = np.load('B_01_J-1_rho_prom_m_100.npy')
rho_prom_e_01 = np.load('B_01_J-1_rho_prom_e_100.npy')


rho_m_1 = np.load('B_1_J-1_rho_m.npy')
rho_e_1 = np.load('B_1_J-1_rho_e.npy')

rho_prom_m_1 = np.load('B_1_J-1_rho_prom_m_100.npy')
rho_prom_e_1 = np.load('B_1_J-1_rho_prom_e_100.npy')

#%% Graficar para termalizacion

plt.figure()

for i in range(range_temp):
    plt.subplot(1,2,1)
    plt.plot(datos[0 : n_iter, 0], datos[i*n_iter : (i+1)*n_iter,1], label = 'T = {:.2f}'.format(temperatura[i]))

    plt.subplot(1,2,2)
    plt.plot(datos[0 : n_iter, 0], datos[i*n_iter : (i+1)*n_iter,2]/(n*n), label = 'T = {:.2f}'.format(temperatura[i]))

plt.subplot(1,2,1)
plt.grid(True)
plt.xlabel('Tiempo')
plt.ylabel('Magnetizacion por sitio')
plt.title('Magnetizacion en el tiempo', fontsize = 15)
plt.legend()

plt.subplot(1,2,2)
plt.grid(True)
plt.xlabel('Tiempo')
plt.ylabel('Energia por sitio')
plt.legend()
plt.title('Energia en el tiempo', fontsize = 15)

plt.show()


#%% Graficar autocorr

plt.figure()
plt.suptitle('Autocorrelacion de magnetizacion y energia', fontsize = 15)

for temp in [1,3,4,9]: #range(range_temp):
    plt.subplot(2,2,1)
    plt.plot(rho_m_01[:,temp], label = 'T = {:.2f}'.format(temperatura[temp]))

    plt.subplot(2,2,2)
    plt.plot(rho_e_01[:,temp], label = 'T = {:.2f}'.format(temperatura[temp]))

    plt.subplot(2,2,3)
    plt.plot(rho_m_1[:,temp], label = 'T = {:.2f}'.format(temperatura[temp]))
    
    plt.subplot(2,2,4)
    plt.plot(rho_e_1[:,temp], label = 'T = {:.2f}'.format(temperatura[temp]))
    
plt.subplot(2,2,1)
plt.legend()
plt.title('B = 0.1', loc = 'left', fontsize = 12)
plt.grid(True)
plt.xlim(0,80000)
plt.xlabel('Tiempo')
plt.ylabel('Autocorrelacion (mag)')

plt.subplot(2,2,2)
plt.legend()
plt.title('B = 0.1', fontsize = 12)
plt.grid(True)
plt.xlim(0,80000)
plt.xlabel('Tiempo')
plt.ylabel('Autocorrelacion (en)')

plt.subplot(2,2,3)
plt.legend()
plt.title('B = 1', fontsize = 12)
plt.grid(True)
plt.xlim(0,80000)
plt.xlabel('Tiempo')
plt.ylabel('Autocorrelacion (mag)')

plt.subplot(2,2,4)
plt.legend()
plt.title('B = 1', fontsize = 12)
plt.grid(True)
plt.xlim(0,80000)
plt.xlabel('Tiempo')
plt.ylabel('Autocorrelacion (en)')

#plt.tight_layout()

plt.show()


#%% Graficar autocorr promediada

plt.figure()
plt.suptitle('Autocorrelacion de magnetizacion y energia', fontsize = 15)

for temp in [1,3,4,9]: #range(range_temp):
    plt.subplot(2,2,1)
    plt.plot(rho_m_01[:,temp], label = 'T = {:.2f}'.format(temperatura[temp]))

    plt.subplot(2,2,2)
    plt.plot(rho_e_01[:,temp], label = 'T = {:.2f}'.format(temperatura[temp]))

    plt.subplot(2,2,3)
    plt.plot(rho_m_1[:,temp], label = 'T = {:.2f}'.format(temperatura[temp]))
    
    plt.subplot(2,2,4)
    plt.plot(rho_e_1[:,temp], label = 'T = {:.2f}'.format(temperatura[temp]))
    
plt.subplot(2,2,1)
plt.legend()
plt.title('B = 0.1', loc = 'left', fontsize = 12)
plt.grid(True)
plt.xlim(0,80000)
plt.xlabel('Tiempo')
plt.ylabel('Autocorrelacion (mag)')

plt.subplot(2,2,2)
plt.legend()
plt.title('B = 0.1', fontsize = 12)
plt.grid(True)
plt.xlim(0,80000)
plt.xlabel('Tiempo')
plt.ylabel('Autocorrelacion (en)')

plt.subplot(2,2,3)
plt.legend()
plt.title('B = 1', fontsize = 12)
plt.grid(True)
plt.xlim(0,80000)
plt.xlabel('Tiempo')
plt.ylabel('Autocorrelacion (mag)')

plt.subplot(2,2,4)
plt.legend()
plt.title('B = 1', fontsize = 12)
plt.grid(True)
plt.xlim(0,80000)
plt.xlabel('Tiempo')
plt.ylabel('Autocorrelacion (en)')

#plt.tight_layout()

plt.show()


